# Generated by Django 2.1 on 2018-09-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sistemas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrarPersonal',
            new_name='Personal',
        ),
    ]
